version: '3.8'
services:
  app:
    build: .
    container_name: historial_medico_app
    ports:
      - "8081:8080" 
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/historial_medico
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: historial_medico_db
    ports:
      - "27017:27017"
